### ISSUE TITLE
Non-void function does not return a value - XCode

### ISSUE THREAD

**Issue by media4learning** [kungfu-king-betty/cordova-plugin-native-app-update#2]
## Your Environment
* Plugin version: 1.0.2
* Platform: iOS
* OS version: 14
* Device manufacturer / model: Apple
* Cordova version (`cordova -v`): Using Capacitor v3
* Cordova platform version (`cordova platform ls`): Using Capacitor v3
* Plugin config

## Expected Behavior
Building project in XCode I get the error 'Non-void function does not return a value' line 68 in CDVAppUpdate.m

## Actual Behavior
Should return a value? Or compile/build

## Steps to Reproduce
1. Create capacitor 3 project and add ios platform
2. npm i cordova-plugin-native-app-update
3. npx cap sync
4. npx cap open ios
5. Select run / build. Build fails

## Context
Use plugin to check for app update on app store. I understand I'm not using this in a cordova project but Capacitor supports Cordova plugins. I suspect the needsUpdate method just needs to return a boolean?

![Screenshot 2021-05-14 at 3 27 09 PM](https://user-images.githubusercontent.com/20275947/118217076-dc744b80-b4c8-11eb-8860-59e3d5165983.png)

**Comment by kungfu-king-betty** [comment]
Hello media! I appreciate you providing so much detail in your issue description, it made tracking down the problem much easier!

Version 1.0.3 was just released, which fixes this issue, so just need to update the plugin and you should be all set. Please let me know if you still have an issue or run into any other problems, thanks!

**Comment by media4learning** [comment]
> Hello media! I appreciate you providing so much detail in your issue description, it made tracking down the problem much easier!
> 
> Version 1.0.3 was just released, which fixes this issue, so just need to update the plugin and you should be all set. Please let me know if you still have an issue or run into any other problems, thanks!

Thanks! I can now build my project, Appreciate your work.
